post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('post/create', views.createPost, name='create_post'),

    path('<str:slug>/', views.post, name='post'),
    path('<str:slug>/edit/', views.updatePost, name='update_post'),
    path('<str:slug>/delete/', views.deletePost, name='delete_post'),

 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('',include('post.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from PIL import Image

def rename_image(instance, filename):
    """Change a image name to post id"""
    _ , extention = filename.split('.')
    return f"posts/{instance.id}.{extention}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='post')
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    categories = models.ManyToManyField(Category, blank=True, help_text='Hold down “Control”, or “Command” on a Mac, to select more than one.')
    photo = models.ImageField(default='posts/default.jpg', upload_to=rename_image)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(null=True, blank=True, unique=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """ make a slug to post, rename a image and resize a big image """
        # Handle a problem when rename a image 
        if self.pk is None:
            image = self.photo
            self.photo = None
            super().save(*args, **kwargs)
            self.photo = image            

        # make a slug before save a post
        post_slug = slugify(self.title)
        self.slug = f"{post_slug}_{self.id}"

        super().save(*args, **kwargs)

        # Resize a image
        img = Image.open(self.photo.path)
        if img.width > 800 or img.height > 800:
            img.thumbnail((800, 800))
            img.save(self.photo.path)

        

class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=80, null=True)
    content = models.TextField(max_length=700)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.content   

post/forms.py
from django.forms import ModelForm
from .models import Post, Comment, Category

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'categories', 'photo')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required 

from .models import Post, Comment
from .forms import PostForm, CommentForm
from .decorators import allowed_users


# Utilities
def same_user(request, post):
    if request.user == post.author or request.user.groups.filter(name='admin').count() != 0:
        return True
    
    return False

def home(request):
    posts = Post.objects.filter(active=True)
    paginator = Paginator(posts, 10)

    page_number = request.GET.get('page')
    
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts':posts,
        'title':'home',
    }
    return render(request, 'post/index.html', context)

def post(request, slug):
    post = get_object_or_404(Post, slug=slug)


    if post.active == True:

        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.post = post
                form.save()


        comments = post.comments.filter(active=True)
        context = {
            'title':post.title,
            'post':post,
            'comments': comments,
        }
        return render(request, 'post/post.html', context)
    else:
        return Http404()
# Post Forms
@login_required(login_url='login')
@allowed_users(allowed_rules=['author', 'ad min'])
def createPost(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.author = request.user
            new_form.save()
            form.save_m2m()
            return redirect('post', slug=new_form.slug)

        else:
            messages.error(request, 'The post not save, some thing wrong please try again')


    context = {
        'title':'Create Post',
        'form':form,
    }
    return render(request,'post/post_form.html', context)

@login_required(login_url='login')
def updatePost(request, slug):
    post = get_object_or_404(Post, slug=slug)

    # Check if logined user is post author or site admin
    if not same_user(request, post):
        return HttpResponse("you not allowed to be here")
    
    form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES, instance=post)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.author = request.user
            new_form.save()
            form.save_m2m()
            return redirect('post', slug=new_form.slug)

        else:
            messages.warning(request, 'The post not save, some thing wrong please try again')


    context = {
        'title':'update Post',
        'form':form,
    }
    return render(request,'post/post_form.html', context)


@login_required(login_url='login')
def deletePost(request, slug):
    post = get_object_or_404(Post, slug=slug)

    # Check if logined user is post author or site admin
    if not same_user(request, post):
        return HttpResponse("you not allowed to be here")


    if request.method == 'POST':
        post.delete()
        messages.warning(request, 'post deleted Successfully')
        return redirect('/')
    
    return render(request, 'post/delete_post.html', {'post':post})

    
def about(request):

    return render(request, 'post/about.html')


def contact(request):

    context = {

    }

    return render(request, 'post/contact.html', context)

post/templates/post/about.html
{% extends 'main.html' %}           
{% load static %}
{% block content %}
            <div class="row tm-row tm-mb-45">
                <div class="col-12">
                    <hr class="tm-hr-primary tm-mb-55">
                    <img src={% static "img/about-01.jpg" %} alt="Image" class="img-fluid">
                </div>
            </div>
            <div class="row tm-row tm-mb-40">
                <div class="col-12">                    
                    <div class="mb-4">
                        <h2 class="pt-2 tm-mb-40 tm-color-primary tm-post-title">About this xtra blog</h2>
                        <p>
                            You can immediately download 
                                <a rel="nofollow" href="https://templatemo.com/tm-553-xtra-blog" target="_blank">Xtra Blog Template</a> 
                                from TemplateMo website for 100% free of charge. Etiam vehicula, tortor ac eleifend tincidunt, diam neque pellentesque ipsum, 
                                a geugiat eros mauris eget lorem. Quisque in
                            bibendum elit, in egestas turpis. Vestibulum ornare sollicitudin congue. Aliquam lorem mi, maximus at iaculis ut, viverra vel
                            mauris. Duis congue luctus metus, sodales tincidunt lectus fringilla ut. Nunc tempus at magna sed vestibulum.
                        </p>
                        <p>
                            Proin et arcu ligula. Praesent quis erat eu est solliditudin tristique ut in arcu. Donec bibendum ex id ligula semper dictum.
                            Proin malesuada luctus auctor. Suspendisse ullamcorper, mi vel molestie ornare, arcu magna euismod ipsum, in
                            malesuada nulla magna ut enim. Morbi lacinia magna sed sapien auctor, vitae luctus nunc cursus.
                        </p>                            
                    </div>                    
                </div>
            </div>
            <div class="row tm-row tm-mb-120">
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fas fa-bezier-curve fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Background</h2>
                        <p class="mb-0 tm-line-height-short">
                            Phasellus pulvinar nisl ornare leo porttitor, et vestibulum lorem semper. 
                            Duis risus ex, molestie sit amet magna in,
                            pharetra pellentesque est. Curabitur elit metus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fas fa-users-cog fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Teamwork</h2>
                        <p class="mb-0 tm-line-height-short">
                            Suspendisse ullamcorper, mi vel molestie ornare, arcu magna euismod ipsum, in malesuada nulla magna ut enim. 
                            Morbi lacinia magna sed auctor, vitae nunc cursus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fab fa-creative-commons-sampling fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Our Core Value</h2>
                        <p class="mb-0 tm-line-height-short">
                            Nunc mi ante, suscipit vel dapibus et, volutpat sit amet ante. In tempor nec sem vitae varius. Aliquam tincidunt orci sem, et imperdiet massa consectetur nec.
                        </p>
                    </div>
                </div>
            </div>            
            <div class="row tm-row tm-mb-60">
                <div class="col-12">
                    <hr class="tm-hr-primary  tm-mb-55">
                </div>                
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src={% static "img/about-02.jpg" %} alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">John Henry</h2>
                            <h3 class="tm-h3 mb-3">CEO/Founder</h3>
                            <p class="mb-0 tm-line-height-short">
                                Aliquam non vulputate lectus, vel ultricies diam. Suspendisse at ipsum
                                hendrerit, vestibulum mi id, mattis tortor.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src={% static "img/about-03.jpg" %} alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Timy Cake</h2>
                            <h3 class="tm-h3 mb-3">Project Director</h3>
                            <p class="mb-0 tm-line-height-short">
                                Quisque in bibendum elit, in egestas turpis. Vestibulum ornare sollicitudin congue. 
                                Aliquam lorem mi, maximus at iaculis ut.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src={% static "img/about-04.jpg" %} alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Jay Zoona</h2>
                            <h3 class="tm-h3 mb-3">Supervisor</h3>
                            <p class="mb-0 tm-line-height-short">
                                Maecenas eu mi eu dui cursus consequat non eu metus. Morbi ac
                                turpis eleifend, commodo purus eget, commodo mauris.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src={% static "img/about-05.jpg" %} alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Catherine Soft</h2>
                            <h3 class="tm-h3 mb-3">Team Leader</h3>
                            <p class="mb-0 tm-line-height-short">
                                Integer eu sapien hendrerit,
                                imperdiet arcu sit amet, sollicitudin ipsum.
                                Phasellus consequat suscipit ligula eget bibendum.
                            </p>
                        </div>
                    </div>
                </div>
            </div>        
{% endblock %}

post/templates/post/comment_form.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-info mb-3" type="submit" value="Create Post ">
        {% if messages %}
            {% for message in messages %}
                <div class="msg">{{messages}}</div>
            {% endfor %}
        {% endif %}
    </form>
{% endblock %}

post/templates/post/contact.html
{% extends 'main.html' %}           

{% block content %}         
            <div class="row tm-row tm-mb-45">
                <div class="col-12">
                    <hr class="tm-hr-primary tm-mb-55">
                    <div class="gmap_canvas"> <!-- Google Map -->
                        <iframe width="100%" height="477" id="gmap_canvas"
                            src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                            frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    </div>
                </div>                
            </div>
            <div class="row tm-row tm-mb-120">
                <div class="col-12">
                    <h2 class="tm-color-primary tm-post-title tm-mb-60">Contact Us</h2>
                </div>
                <div class="col-lg-7 tm-contact-left">
                    <form method="POST" action="" class="mb-5 ml-auto mr-0 tm-contact-form">                        
                        <div class="form-group row mb-4">
                            <label for="name" class="col-sm-3 col-form-label text-right tm-color-primary">Name</label>
                            <div class="col-sm-9">
                                <input class="form-control mr-0 ml-auto" name="name" id="name" type="text" required>                            
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label for="email" class="col-sm-3 col-form-label text-right tm-color-primary">Email</label>
                            <div class="col-sm-9">
                                <input class="form-control mr-0 ml-auto" name="email" id="email" type="email" required>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label for="subject" class="col-sm-3 col-form-label text-right tm-color-primary">Subject</label>
                            <div class="col-sm-9">
                                <input class="form-control mr-0 ml-auto" name="subject" id="subject" type="text" required>
                            </div>
                        </div>
                        <div class="form-group row mb-5">
                            <label for="message" class="col-sm-3 col-form-label text-right tm-color-primary">Message</label>
                            <div class="col-sm-9">
                                <textarea class="form-control mr-0 ml-auto" name="message" id="message" rows="8" required></textarea>                                
                            </div>
                        </div>
                        <div class="form-group row text-right">
                            <div class="col-12">
                                <button class="tm-btn tm-btn-primary tm-btn-small">Submit</button>                        
                            </div>                            
                        </div>                                
                    </form>
                </div>
                <div class="col-lg-5 tm-contact-right">
                    <address class="mb-4 tm-color-gray">
                        120 Lorem ipsum dolor sit amet,
                        consectetur adipiscing 10550
                    </address>
                    <span class="d-block">
                        Tel:
                        <a href="tel:060-070-0980" class="tm-color-gray">060-070-0980</a>
                    </span>
                    <span class="mb-4 d-block">
                        Email:
                        <a href="mailto:info@company.com" class="tm-color-gray">info@company.com</a>
                    </span>
                    <p class="mb-5 tm-line-height-short">
                        Maecenas eu mi eu dui cursus
                        consequat non eu metus. Morbi ac
                        turpis eleifend, commodo purus
                        eget, commodo mauris.
                    </p>
                    <ul class="tm-social-links">
                        <li class="mb-2">
                            <a href="https://facebook.com" class="d-flex align-items-center justify-content-center">
                                <i class="fab fa-facebook"></i>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a href="https://twitter.com" class="d-flex align-items-center justify-content-center">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a href="https://youtube.com" class="d-flex align-items-center justify-content-center">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a href="https://instagram.com" class="d-flex align-items-center justify-content-center mr-0">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>      

{% endblock %}

post/templates/post/delete_comment.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form  method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{comment.content}}</p>
        <input class="btn btn-danger m-2" type="submit" value="Delete comment ">
        <a class="btn btn-info m-2" href="/">Cancel</a>
    </form>
{% endblock %}

post/templates/post/delete_post.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form  method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{post.title}}</p>
        <input class="btn btn-danger m-2" type="submit" value="Delete Post ">
        <a class="btn btn-info m-2" href="/">Cancel</a>
    </form>
{% endblock %}

post/templates/post/last_comments.html
<h2 class="mb-4 tm-post-title tm-color-primary">last Comment</h2>
                        <ul class="tm-mb-75 pl-5 tm-category-list">
                            {% for comment in latest_comments %}
                            <li><a href="{% url 'post' comment.post.slug %}" class="tm-color-primary">{{comment.content|slice:"0:40"}}</a></li>
                            {% endfor %}
                        </ul>

post/templates/post/last_posts.html
<hr class="mb-3 tm-hr-primary">
<h2 class="tm-mb-40 tm-post-title tm-color-primary">Related Posts</h2>
{% for post in last_posts %}
<a href="{% url 'post' post.slug %}" class="d-block tm-mb-40">
    <figure>
        <figcaption class="tm-color-primary">{{post.title}}</figcaption>
        <img src="{{post.photo.url}}" alt="Image" class="mb-3 img-fluid" style="width: 200px;">
    </figure>
</a>
{% endfor %}

post/templates/post/post.html
{% extends 'main.html' %}           
{% load post_extras %}
{% load static %}
{% block content %}
            <div class="row tm-row">
                <div class="col-12">
                    {% include 'post/search.html' %}
                    <hr class="tm-hr-primary tm-mb-55">

                    {% if request.user == post.author %}
                        <a class="btn btn-lg btn-info m-3" href="{% url 'update_post' post.slug %}">Update  post</a>
                        <a class="btn btn-lg btn-danger m-3" href="{% url 'delete_post' post.slug %}">Delete post</a>
                    {% endif %}

                    <img width="954" height="535" controls class="tm-mb-40" src="{{post.photo.url}}">
                </div>
            </div>
            <div class="row tm-row">
                <div class="col-lg-8 tm-post-col">
                    <div class="tm-post-full">                    
                        <div class="mb-4">
                            <h2 class="pt-2 tm-color-primary tm-post-title">{{post.title}}</h2>
                            <p class="tm-mb-40">{{post.created_at|date:'F d, Y'}} posted by {{post.author}}</p>
                            <p>
                                {{post.content}}
                            </p>
                            <span class="d-block text-right tm-color-primary">
                                {% for category in post.categories.all %}
                                {{category}}{% if not forloop.last %} .{% endif %}
                                {% empty %}
                                <p>There is no categories</p>
                            {% endfor %}
                            </span>
                        </div>
                        
                        <!-- Comments -->
                        <div>
                            <h2 class="tm-color-primary tm-post-title">Comments</h2>
                            <hr class="tm-hr-primary tm-mb-45">
                            {% for comment in comments|slice:'0:15' %}
                            <div class="tm-comment tm-mb-45">
                                <figure class="tm-comment-figure">
                                    <img src="{% static 'img/comment-1.jpg' %}" alt="Image" class="mb-2 rounded-circle img-thumbnail">
                                    <figcaption class="tm-color-primary text-center">{{comment.name}}</figcaption>
                                </figure>
                                <div>
                                    <p>
                                       {{comment.content}}
                                    </p>
                                    <span class="tm-color-primary">{{comment.created_at|date:'F d, Y'}}</span>
                                
                                </div>  

                            </div>
                            <hr>
                            <!-- <div class="tm-comment-reply tm-mb-45">
                                <hr>
                                <div class="tm-comment">
                                    <figure class="tm-comment-figure">
                                        <img src="img/comment-2.jpg" alt="Image" class="mb-2 rounded-circle img-thumbnail">
                                        <figcaption class="tm-color-primary text-center">Jewel Soft</figcaption>    
                                    </figure>
                                    <p>
                                        Nunc et eros quis enim feugiat tincidunt et vitae dui.
                                        Nullam consectetur justo ac ex laoreet rhoncus. Nunc
                                        id leo pretium, faucibus sapien vel, euismod turpis.
                                    </p>
                                </div>                                
                                <span class=
                                "d-block text-right tm-color-primary">June 21, 2020</span>
                            </div> -->
                            {% endfor %}                              

                            <form method='POST' class="mb-5 tm-comment-form">
                                
                                {% csrf_token %}

                                <h2 class="tm-color-primary tm-post-title mb-4">Your comment</h2>
                                <div class="mb-4">
                                    <label for="id_name">Name</label>
                                    <input class="form-control" name="name" required_id='id_name' type="text">
                                </div>
                                <div class="mb-4">
                                    <label for="id_email">Email</label>
                                    <input class="form-control" name="email" required_id="id_email" type="email">
                                </div>
                                <div class="mb-4">
                                    <label for="id_content">Content</label>
                                    <textarea class="form-control" name="content" required_id="id_content" rows="6"></textarea>
                                </div>
                                <div class="text-right">
                                    <input class="tm-btn tm-btn-primary tm-btn-small" type="submit" value="Submit">
                                </div>                                
                            </form>                          
                        </div>
                    </div>
                </div>
                <aside class="col-lg-4 tm-aside-col">
                    <div class="tm-post-sidebar">
                        <hr class="mb-3 tm-hr-primary">
                        {% show_last_comments %}
                        {% show_last_posts %}
                       
                    </div>                    
                </aside>
            </div>
   
            
{% endblock %}

post/templates/post/post_form.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-info mb-3" type="submit" value="Create Post ">
        {% if messages %}
            {% for message in messages %}
                <div class="msg">{{messages}}</div>
            {% endfor %}
        {% endif %}
    </form>
{% endblock %}

post/templates/post/search.html
 <!-- Search form -->
 <div class="row tm-row">
    <div class="col-12">
        <form method="GET" class="form-inline tm-mb-80 tm-search-form">                
            <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
            <button class="tm-search-button" type="submit">
                <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
            </button>                                
        </form>
    </div>                
</div> 